apiVersion : apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app : backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1 #count of saved replicaset to return by kubectl rollout deployment
  selector:
    matchLabels:
      project: nginx-backend
  template:
    metadata:
      labels:
        project: nginx-backend
    spec:
      containers:
        - name : nginx-backend-container
          image: firebelka/nginx:v2
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: docker-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-svc
  labels:
    env  : prod
spec:
  selector:
    project: nginx-backend    # Selecting PODS with those Labels
  ports:
    - port : 80  # Port on Load Balance
      targetPort: 8081
  type: ClusterIP
